spring.application.name=codetickets

# configuracao para conexao com banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/codetickets_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


# configuracao para inicializar tabelas de registro de execucao dos jobs
spring.batch.initialize-schema=always

# configuracao para atualizar banco de dados com as alteracoes de entidades
spring.jpa.hibernate.ddl-auto=update